version: '3.8'
services:
  db:
    image: postgres:13.3
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: app/
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL: admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD: admin
    valumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
