version: '3.8'
services:
  db:
    image: postgres:13.3
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
  app:
    image: nikuma0/random_coffe_bot:latest
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  db_data: